import { Img } from './img'

export var IMG:Img[]=[{
    id:1,
    src:"http://om1o3l1z1.bkt.clouddn.com/1.jpeg",
    title:"晏几道",
    caption:"晏几道",
    desc:"今日政事堂中半吾家旧客，亦未暇见也。"
},{
    id:2,
    src:"http://om1o3l1z1.bkt.clouddn.com/2.jpeg",
    title:"晏几道",
    caption:"晏几道",
    desc:"今日政事堂中半吾家旧客，亦未暇见也。"
},{
    id:3,
    src:"http://om1o3l1z1.bkt.clouddn.com/3.jpeg",
    title:"晏几道",
    caption:"晏几道",
    desc:"今日政事堂中半吾家旧客，亦未暇见也。"
},{
    id:4,
    src:"http://om1o3l1z1.bkt.clouddn.com/4.jpeg",
    title:"晏几道",
    caption:"晏几道",
    desc:"今日政事堂中半吾家旧客，亦未暇见也。"
},{
    id:5,
    src:"http://om1o3l1z1.bkt.clouddn.com/5.jpeg",
    title:"晏几道",
    caption:"晏几道",
    desc:"今日政事堂中半吾家旧客，亦未暇见也。"
},{
    id:6,
    src:"http://om1o3l1z1.bkt.clouddn.com/6.jpeg",
    title:"晏几道",
    caption:"晏几道",
    desc:"今日政事堂中半吾家旧客，亦未暇见也。"
},{
    id:7,
    src:"http://om1o3l1z1.bkt.clouddn.com/7.jpeg",
    title:"晏几道",
    caption:"晏几道",
    desc:"今日政事堂中半吾家旧客，亦未暇见也。"
},{
    id:8,
    src:"http://om1o3l1z1.bkt.clouddn.com/8.jpeg",
    title:"晏几道",
    caption:"晏几道",
    desc:"今日政事堂中半吾家旧客，亦未暇见也。"
},{
    id:9,
    src:"http://om1o3l1z1.bkt.clouddn.com/9.jpeg",
    title:"晏几道",
    caption:"晏几道",
    desc:"今日政事堂中半吾家旧客，亦未暇见也。"
},{
    id:10,
    src:"http://om1o3l1z1.bkt.clouddn.com/10.jpeg",
    title:"晏几道",
    caption:"晏几道",
    desc:"今日政事堂中半吾家旧客，亦未暇见也。"
},{
    id:11,
    src:"http://om1o3l1z1.bkt.clouddn.com/11.jpeg",
    title:"晏几道",
    caption:"晏几道",
    desc:"今日政事堂中半吾家旧客，亦未暇见也。"
},{
    id:12,
    src:"http://om1o3l1z1.bkt.clouddn.com/12.jpeg",
    title:"晏几道",
    caption:"晏几道",
    desc:"今日政事堂中半吾家旧客，亦未暇见也。"
},{
    id:13,
    src:"http://om1o3l1z1.bkt.clouddn.com/13.jpeg",
    title:"晏几道",
    caption:"晏几道",
    desc:"今日政事堂中半吾家旧客，亦未暇见也。"
},{
    id:14,
    src:"http://om1o3l1z1.bkt.clouddn.com/14.jpeg",
    title:"晏几道",
    caption:"晏几道",
    desc:"今日政事堂中半吾家旧客，亦未暇见也。"
},{
    id:15,
    src:"http://om1o3l1z1.bkt.clouddn.com/15.jpeg",
    title:"晏几道",
    caption:"晏几道",
    desc:"今日政事堂中半吾家旧客，亦未暇见也。"
}]
   